apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app.kubernetes.io/name: kyd-invest
    app.kubernetes.io/version: 1.0.2-SNAPSHOT
    app.openshift.io/runtime: quarkus
    generateby: quarkus-plugin
    kubernetes.io/part-of: quant-invest
  name: kyd-invest
  namespace: classic-dev
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app.kubernetes.io/name: kyd-invest
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/build-timestamp: 2022-02-17 - 08:08:27 +0000
        app.quarkus.io/commit-id: 81ae1648e742f55f898b0d5fa14f73dc0f702966
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kyd-invest
        app.kubernetes.io/version: 1.0.2-SNAPSHOT
        app.openshift.io/runtime: quarkus
        generateby: quarkus-plugin
        kubernetes.io/part-of: quant-invest
      namespace: classic-dev
    spec:
      containers:
      - command:
        - java
        - -Dquarkus.http.host=0.0.0.0
        - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
        - -jar
        - /deployments/quarkus-run.jar
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: TZ
          value: Asia/Shanghai
        - name: JAVA_APP_JAR
          value: /deployments/kyd-invest-1.0.2-SNAPSHOT-runner.jar
        image: image-registry.openshift-image-registry.svc:5000/classic-dev/kyd-invest@sha256:3c2a47aa59639eaeec44c72d05d67954dc65ff99a392ff9d92f36e8ac34b45ac
        imagePullPolicy: IfNotPresent
        name: kyd-invest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /jboss/home/config/application.properties
          name: application-properties-volume
          subPath: application.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 272
          name: kyd-invest-main-config
          optional: false
        name: application-properties-volume
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - kyd-invest
      from:
        kind: ImageStreamTag
        name: kyd-invest:1.0.2-SNAPSHOT
        namespace: classic-dev
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/classic-dev/kyd-invest@sha256:3c2a47aa59639eaeec44c72d05d67954dc65ff99a392ff9d92f36e8ac34b45ac
    type: ImageChange
