--- 
apiVersion: v1
data: 
  application.properties: "# Rest API\n\
      quarkus.http.auth.form.landing-page=/index.html\n\
      ## DEV Override\n\
      %dev.quarkus.http.port=8088\n\
      # Datasource\n\
      quarkus.datasource.db-kind=postgresql\n\
      quarkus.datasource.username=user\n\
      quarkus.datasource.password=password\n\
      quarkus.datasource.jdbc.url=jdbc:postgresql://pg-quant-invest:5432/market?currentSchema=invest\n\
      quarkus.datasource.jdbc.max-size=10\n\
      # Flyway\n\
      quarkus.flyway.create-schemas=true\n\
      quarkus.flyway.schemas=invest\n\
      %dev.quarkus.flyway.schemas=INVEST\n\
      %test.quarkus.flyway.schemas=INVEST\n\
      quarkus.flyway.validate-on-migrate=true\n\
      quarkus.flyway.migrate=true\n\n\
      quarkus.flyway.baseline-on-migrate=true\n\
      quarkus.flyway.locations=db/migration,db/specific/postgresql\n\
      quarkus.flyway.migrate-at-start=true\n\
      quarkus.flyway.baseline-version=0\n\
      ## DEV Overrides\n\
      %dev.quarkus.datasource.db-kind=h2\n\
      %dev.quarkus.datasource.username=sa\n\
      %dev.quarkus.datasource.password=password\n\
      %dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:market;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS INVEST;\n\
      %dev.quarkus.datasource.jdbc.max-size=10\n\
      %dev.quarkus.flyway.locations=db/migration,db/specific/h2\n\
      #%dev.quarkus.flyway.migrate=false\n\
      ## TEST Overrides\n\
      %test.quarkus.datasource.db-kind=h2\n\
      %test.quarkus.datasource.username=sa\n\
      %test.quarkus.datasource.password=password\n\
      %test.quarkus.datasource.jdbc.url=jdbc:h2:mem:market;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS INVEST;\n\
      %test.quarkus.datasource.jdbc.max-size=10\n\
      %test.quarkus.flyway.locations=db/migration,db/specific/h2\n\
      #%test.quarkus.flyway.migrate=false\n\
      #JPA 配置\n\
      quarkus.hibernate-orm.database.generation=none\n\
      quarkus.hibernate-orm.log.sql=false\n\
      ## DEV Config Overrides\n\
      %dev.quarkus.hibernate-orm.database.generation=drop-and-create\n\
      #%dev.quarkus.hibernate-orm.database.generation=none\n\
      %dev.quarkus.hibernate-orm.log.sql=true\n\n\
      # Logging\n\
      quarkus.banner.enabled=true\n\
      quarkus.log.level=INFO\n\
      quarkus.log.file.enable=true\n\
      quarkus.log.file.level=INFO\n\
      quarkus.log.file.path=/tmp/kys-app.log\n\n\
      ## DEV Profile Config Overrides\n\
      %dev.quarkus.log.console.color=true\n\
      %dev.quarkus.log.console.json=false\n\
      %test.quarkus.log.console.json=false\n\n\
      # OpenShift\n\
      quarkus.kubernetes-client.trust-certs=true\n\
      quarkus.openshift.route.expose=true\n\
      quarkus.openshift.labels.generateby=quarkus-plugin\n\n\
      quarkus.openshift.mounts.application-properties-volume.path=/jboss/home/config/application.properties\n\
      quarkus.openshift.mounts.application-properties-volume.sub-path=application.properties\n\
      quarkus.openshift.config-map-volumes.application-properties-volume.config-map-name=kyd-invest-main-config\n\
      quarkus.openshift.config-map-volumes.application-properties-volume.default-mode=0420\n\
      quarkus.openshift.route.annotations.\"haproxy.router.openshift.io/timeout\"=60s\n\
      quarkus.openshift.labels.\"kubernetes.io/part-of\"=quant-invest\n\
      quarkus.openshift.env.vars.TZ=Asia/Shanghai\n\n\n\
      # Restful Cli\n\
      countries-api/mp-rest/url=https://restcountries.com\n\
      countries-api/mp-rest/scope=javax.inject.Singleton\n\
      countries-api/mp-rest/hostnameVerifier=io.quarkus.restclient.NoopHostnameVerifier\n\
      # countries-api/mp-rest/proxyAddress=app-proxy.cgc.com.my:3128\n\n\n\
      # Test google api since googleapi require httpproxy\n\
      # google-api/mp-rest/url=https://www.youtube.com\n\
      # google-api/mp-rest/proxyAddress=192.168.2.15:3128\n\
      # google-api/mp-rest/connectTimeout=3000\n\
      # google-api/mp-rest/readTimeout=3000\n\n\
      product-api/mp-rest/url=http://localhost:8081\n\
      product-api/mp-rest/scope=javax.inject.Singleton\n\
      product-api/mp-rest/hostnameVerifier=io.quarkus.restclient.NoopHostnameVerifier\n\n\
      # quarkus.tls.trust-all=true\n"
kind: ConfigMap
metadata: 
  name: kyd-invest-main-config
  namespace: quant-invest
